export type Currency = { code: string; name: string; country: string; symbol: string };

export const CURRENCIES: Currency[] = [
  { code: "USD", name: "US Dollar", country: "United States", symbol: "$" },
  { code: "EUR", name: "Euro", country: "European Union", symbol: "€" },
  { code: "GBP", name: "Pound Sterling", country: "United Kingdom", symbol: "£" },
  { code: "JPY", name: "Japanese Yen", country: "Japan", symbol: "¥" },
  { code: "CNY", name: "Chinese Yuan", country: "China", symbol: "¥" },
  { code: "CAD", name: "Canadian Dollar", country: "Canada", symbol: "C$" },
  { code: "AUD", name: "Australian Dollar", country: "Australia", symbol: "A$" },
  { code: "NZD", name: "New Zealand Dollar", country: "New Zealand", symbol: "NZ$" },
  { code: "CHF", name: "Swiss Franc", country: "Switzerland", symbol: "CHF" },
  { code: "SEK", name: "Swedish Krona", country: "Sweden", symbol: "kr" },
  { code: "NOK", name: "Norwegian Krone", country: "Norway", symbol: "kr" },
  { code: "DKK", name: "Danish Krone", country: "Denmark", symbol: "kr" },
  { code: "SGD", name: "Singapore Dollar", country: "Singapore", symbol: "S$" },
  { code: "HKD", name: "Hong Kong Dollar", country: "Hong Kong", symbol: "HK$" },
  { code: "INR", name: "Indian Rupee", country: "India", symbol: "₹" },
  { code: "PKR", name: "Pakistani Rupee", country: "Pakistan", symbol: "₨" },
  { code: "BDT", name: "Bangladeshi Taka", country: "Bangladesh", symbol: "৳" },
  { code: "MYR", name: "Malaysian Ringgit", country: "Malaysia", symbol: "RM" },
  { code: "THB", name: "Thai Baht", country: "Thailand", symbol: "฿" },
  { code: "PHP", name: "Philippine Peso", country: "Philippines", symbol: "₱" },
  { code: "IDR", name: "Indonesian Rupiah", country: "Indonesia", symbol: "Rp" },
  { code: "VND", name: "Vietnamese Dong", country: "Vietnam", symbol: "₫" },
  { code: "KRW", name: "South Korean Won", country: "South Korea", symbol: "₩" },
  { code: "TWD", name: "Taiwan Dollar", country: "Taiwan", symbol: "NT$" },
  { code: "NGN", name: "Nigerian Naira", country: "Nigeria", symbol: "₦" },
  { code: "GHS", name: "Ghanaian Cedi", country: "Ghana", symbol: "₵" },
  { code: "KES", name: "Kenyan Shilling", country: "Kenya", symbol: "KSh" },
  { code: "UGX", name: "Ugandan Shilling", country: "Uganda", symbol: "USh" },
  { code: "TZS", name: "Tanzanian Shilling", country: "Tanzania", symbol: "TSh" },
  { code: "RWF", name: "Rwandan Franc", country: "Rwanda", symbol: "FRw" },
  { code: "ETB", name: "Ethiopian Birr", country: "Ethiopia", symbol: "Br" },
  { code: "ZAR", name: "South African Rand", country: "South Africa", symbol: "R" },
  { code: "ZMW", name: "Zambian Kwacha", country: "Zambia", symbol: "ZK" },
  { code: "BWP", name: "Botswana Pula", country: "Botswana", symbol: "P" },
  { code: "EGP", name: "Egyptian Pound", country: "Egypt", symbol: "£" },
  { code: "MAD", name: "Moroccan Dirham", country: "Morocco", symbol: "DH" },
  { code: "TND", name: "Tunisian Dinar", country: "Tunisia", symbol: "DT" },
  { code: "DZD", name: "Algerian Dinar", country: "Algeria", symbol: "DA" },
  { code: "XOF", name: "West African CFA", country: "West Africa", symbol: "CFA" },
  { code: "XAF", name: "Central African CFA", country: "Central Africa", symbol: "FCFA" },
  { code: "AED", name: "UAE Dirham", country: "United Arab Emirates", symbol: "د.إ" },
  { code: "SAR", name: "Saudi Riyal", country: "Saudi Arabia", symbol: "﷼" },
  { code: "QAR", name: "Qatari Riyal", country: "Qatar", symbol: "﷼" },
  { code: "KWD", name: "Kuwaiti Dinar", country: "Kuwait", symbol: "KD" },
  { code: "BHD", name: "Bahraini Dinar", country: "Bahrain", symbol: "BD" },
  { code: "OMR", name: "Omani Rial", country: "Oman", symbol: "﷼" },
  { code: "JOD", name: "Jordanian Dinar", country: "Jordan", symbol: "JD" },
  { code: "ILS", name: "Israeli Shekel", country: "Israel", symbol: "₪" },
  { code: "TRY", name: "Turkish Lira", country: "Türkiye", symbol: "₺" },
  { code: "BRL", name: "Brazilian Real", country: "Brazil", symbol: "R$" },
  { code: "MXN", name: "Mexican Peso", country: "Mexico", symbol: "Mex$" },
  { code: "ARS", name: "Argentine Peso", country: "Argentina", symbol: "$" },
  { code: "CLP", name: "Chilean Peso", country: "Chile", symbol: "$" },
  { code: "COP", name: "Colombian Peso", country: "Colombia", symbol: "Col$" },
  { code: "PEN", name: "Peruvian Sol", country: "Peru", symbol: "S/." },
  { code: "VES", name: "Venezuelan Bolívar", country: "Venezuela", symbol: "Bs" },
  { code: "UYU", name: "Uruguayan Peso", country: "Uruguay", symbol: "$U" },
  { code: "CZK", name: "Czech Koruna", country: "Czech Republic", symbol: "Kč" },
  { code: "PLN", name: "Polish Złoty", country: "Poland", symbol: "zł" },
  { code: "HUF", name: "Hungarian Forint", country: "Hungary", symbol: "Ft" },
  { code: "RON", name: "Romanian Leu", country: "Romania", symbol: "lei" },
  { code: "BGN", name: "Bulgarian Lev", country: "Bulgaria", symbol: "лв" },
  { code: "HRK", name: "Croatian Kuna", country: "Croatia", symbol: "kn" },
  { code: "RSD", name: "Serbian Dinar", country: "Serbia", symbol: "дин" },
  { code: "UAH", name: "Ukrainian Hryvnia", country: "Ukraine", symbol: "₴" },
  { code: "RUB", name: "Russian Ruble", country: "Russia", symbol: "₽" },
  { code: "KZT", name: "Kazakhstani Tenge", country: "Kazakhstan", symbol: "₸" },
  { code: "UZS", name: "Uzbek Som", country: "Uzbekistan", symbol: "сўм" },
  { code: "GEL", name: "Georgian Lari", country: "Georgia", symbol: "₾" },
  { code: "AMD", name: "Armenian Dram", country: "Armenia", symbol: "֏" },
  { code: "AZN", name: "Azerbaijani Manat", country: "Azerbaijan", symbol: "₼" },
  { code: "BYN", name: "Belarusian Ruble", country: "Belarus", symbol: "Br" },
  { code: "MDL", name: "Moldovan Leu", country: "Moldova", symbol: "L" },
  { code: "ISK", name: "Icelandic Króna", country: "Iceland", symbol: "kr" },
];

export const CURRENCY_CODES = CURRENCIES.map(c => c.code);
